// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entity;

public partial class Booking
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public int ClassScheduleId { get; set; }

    public int CreditsDeducted { get; set; }

    public string Status { get; set; }

    public DateTime BookingDate { get; set; }

    public bool CheckedIn { get; set; }

    public int? UserPackageId { get; set; }

    public virtual ClassSchedule ClassSchedule { get; set; }

    public virtual User User { get; set; }

    public virtual UserPackage UserPackage { get; set; }
}