// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entity;

public partial class ClassSchedule
{
    public int Id { get; set; }

    public string Name { get; set; }

    public DateTime StartTime { get; set; }

    public DateTime EndTime { get; set; }

    public int RequiredCredits { get; set; }

    public int MaxCapacity { get; set; }

    public int CountryId { get; set; }

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    public virtual Country Country { get; set; }

    public virtual ICollection<Waitlist> Waitlists { get; set; } = new List<Waitlist>();
}