// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entity;

public partial class UserPackage
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public int PackageId { get; set; }

    public int RemainingCredits { get; set; }

    public DateTime PurchaseDate { get; set; }

    public DateTime ExpiryDate { get; set; }

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    public virtual Package Package { get; set; }

    public virtual User User { get; set; }
}