// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entity;

public partial class Waitlist
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public int ClassScheduleId { get; set; }

    public DateTime WaitlistDate { get; set; }

    public int Order { get; set; }

    public int CreditsDeducted { get; set; }

    public bool IsCreditRefunded { get; set; }

    public virtual ClassSchedule ClassSchedule { get; set; }

    public virtual User User { get; set; }
}